### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by mxwlsavard** [robert-alfaro/xfinity-usage#2] opened 2019-12-14 20:36 UTC
Hey Robert, thanks for this component! Is there any way to make it work with 2FA enabled? 🤔

**Comment by degan6** [comment] 2019-12-15 01:12
I had this problem as well, I got around it by creating another user on my Comcast account without 2fa.

**Comment by robert-alfaro** [comment] 2019-12-17 09:06
I'm not sure this would work with 2FA because typically the way real integrations work...this would use an API with some authentication token. Since this is more of a scraper, I don't see this easily done (to my knowledge).

**Comment by mxwlsavard** [comment] 2019-12-21 03:37
That’s understandable.  Degan’s idea of a second user works as a workaround. Thanks again!

**Comment by robert-alfaro** [comment] 2020-01-09 00:36
Closing this issue as I don't think it's going to happen. In the event anything changes, we can re-open.

**Closed as completed by robert-alfaro** 2020-01-09 00:36 UTC

**Comment by mike-mo** [comment] 2023-01-08 17:21
@degan6 given that such a secondary account would be less secure by design, what is the lowest level of access that needs to be granted for it to be able to monitor bandwidth usage against the data cap?

From https://customer.xfinity.com/settings/users/add

> Select what they'll have access to
>
> # Manager
>
>    Payments and billing preferences
>    Review/discuss account issues (like past-due balances)
>    Troubleshoot and schedule appointments
>    Change or customize plan
>    Service and device settings
>    All Xfinity service apps
>    Cannot transfer service to a new address or manage other people on this account
>
> # Member
>
>    Troubleshoot
>    Service and device settings
>    All Xfinity service apps
>    No access to billing, plan, or appointments
> 
> # Viewer
>    Access to Xfinity Stream app
>    No access to billing, plan, or appointments
